services : 

  postgres :
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment :
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports :
      - "5432:5432"
    volumes :
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lastbench"]
      interval: 5s
      timeout: 2s
      retries: 10

  # garage :
  #   image: dxflrs/garage:v0.8.1
  #   container_name: garage-server
  #   restart: always
  #   ports :
  #     - "3900:3900"
  #     - "3901:3901"
  #     - "3902:3902"
  #     - "3903:3903"
  #   volumes :
  #     - garage_data:/var/lib/garage/data
  #     - garage_meta:/var/lib/garage/meta
  #     - ./garage.toml:/etc/garage.toml
  #   environment :
  #     RUST_LOG: garage=info # can use garage=debug for more detailed logs

  seaweedfs :
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    restart: always
    ports :
      - "9333:9333"   #master server
      - "8080:8080"   #volume server
      - "8888:8888"   #filer server
      - "8333:8333"   #s3 api
    volumes :
      - seaweedfs_data:/data
      - ./seaweedfs-config.json:/etc/seaweedfs/s3.json
    command: 'server -s3 -s3.port=8333 -s3.config=/etc/seaweedfs/s3.json -dir=/data'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9333/cluster/status"]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  postgres_data:
  seaweedfs_data: